In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
pd.set_option('display.max_columns', None) # apresentar todas as colunas do Dataframe
# pd.set_option('display.float_format', '{:.4f}'.format)
pd.set_option('display.float_format', lambda x: '%.3f' % x)

# 3. NewsItemsReplies

In [5]:
missing_values = ['n\a', 'na', 'None', 'NaN', '--', '.']

In [6]:
ireplies = pd.read_csv('NewsItemsReplies.csv', low_memory=False, na_values = missing_values)
ireplies.head()

,comment_id,news_tweet_text,comment_tweet_date,in_reply_to_news_id,comment_tweet_text,perspective_attack_on_author,perspective_attack_on_commenter,perspective_identity_attack,perspective_inflammatory,perspective_insult,perspective_profanity,perspective_severe_toxicity,perspective_threat,perspective_toxicity
0,1084048846781583360,People over 65 and ultra conservatives shared ...,2019-01-12 11:23:05,1084048113260773377,@ABC Probably because Conservatives are the sa...,0.004,0.654,0.293,0.397,0.445,0.227,0.109,0.152,0.387
1,1081750348010872832,OPINION: Congresswoman Rashida Tlaib should ap...,2019-01-05 23:24:52,1081693041222709249,@ABC @matthewjdowd Have you forgotten who she ...,0.127,0.912,0.417,0.651,0.419,0.319,0.315,0.460,0.500
2,1083125706689822720,Rep. Kevin McCarthy disputes Sen. Schumer's ac...,2019-01-09 21:39:48,1083116150660055040,@ABC Democratic Neanderthals! Who doesn’t like...,0.055,0.386,0.346,0.568,0.491,0.367,0.237,0.234,0.441
3,1081555613098889216,OPINION: Congresswoman Rashida Tlaib should ap...,2019-01-05 11:06:13,1081507153721114629,@ABC @matthewjdowd When Trump apologizes is wh...,0.019,0.300,0.134,0.227,0.160,0.150,0.087,0.157,0.224
4,1081279148612571137,JUST IN: Pres. Trump says he's considered decl...,2019-01-04 19:55:11,1081277886105976832,@ABC That continent is stuck with the baggage ...,0.025,0.592,0.331,0.568,0.593,0.485,0.341,0.353,0.618

### Duplicados

In [7]:
ireplies.drop_duplicates(inplace=True)

## Notação científica

In [11]:
items.loc[items['news_id'] == 1080101339156369408]

Empty DataFrame
Columns: [news_id, newsoutlet_id, news_tweet_date, news_url, new_title, news_date, news_text, single_news_id]
Index: []

In [8]:
## DROP_DUPLICATES CONDICIONADO ##
# Ordena IN_REPLY_TO_NEWS_ID de forma a que estejam primeiro os que estão 
# em notação cientifica e, por fim, elimina os duplicados mantendo só os 
# últimos que terão o formato normal, caso existam.

ireplies.sort_values('in_reply_to_news_id',inplace=True)
ireplies.drop_duplicates(['comment_id','news_tweet_text','comment_tweet_date',
                          'comment_tweet_text'], keep='last', inplace=True)
ireplies

,comment_id,news_tweet_text,comment_tweet_date,in_reply_to_news_id,comment_tweet_text,perspective_attack_on_author,perspective_attack_on_commenter,perspective_identity_attack,perspective_inflammatory,perspective_insult,perspective_profanity,perspective_severe_toxicity,perspective_threat,perspective_toxicity
162471,"1,07836665916813E+018",Michelle Obama named America's most admired wo...,2018-12-27 16:09:32,"1,07832199495598E+018",@CBSNews Bahahaha: (1) that’s a dude,0.014,0.345,0.150,0.068,0.170,0.164,0.162,0.202,0.189
162478,"1,07953981201571E+018",The return of slapstick comedy duo Laurel &amp,2018-12-31 00:29:50,"1,07953506114843E+018",@CBSNews أنين الصمت يقدم ⚔ #Thala عيدكم دماء...,0.000,0.004,0.268,0.007,0.193,0.235,0.278,0.383,0.232
162495,"1,0795680349797E+018",The return of slapstick comedy duo Laurel &amp,2018-12-31 00:29:50,"1,07953506114843E+018",@CBSNews They were Comedian Magicians,0.011,0.212,0.145,0.183,0.241,0.144,0.150,0.244,0.231
162480,"1,07953638549164E+018",The return of slapstick comedy duo Laurel &amp,2018-12-31 00:29:50,"1,07953506114843E+018",@CBSNews Is this word play for the return of d...,0.012,0.417,0.160,0.193,0.093,0.036,0.024,0.073,0.142
162489,"1,07953567324437E+018",The return of slapstick comedy duo Laurel &amp,2018-12-31 00:29:50,"1,07953506114843E+018",@CBSNews Liberals will declare their comedy ro...,0.005,0.536,0.694,0.728,0.524,0.293,0.325,0.249,0.599
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109718,1084622008690847744,With a new Democratic ally in the governor's o...,2019-01-14 01:22:18,1084621697418973184,@ABC How about also enforcing laws regarding t...,0.017,0.269,0.264,0.106,0.187,0.160,0.164,0.411,0.233
19833,1084622531695235072,With a new Democratic ally in the governor's o...,2019-01-14 01:22:18,1084621697418973184,@ABC https://t.co/kOOf2UMzpf,0.029,0.304,0.174,0.103,0.124,0.128,0.130,0.270,0.162
16896,1084622234797383682,With a new Democratic ally in the governor's o...,2019-01-14 01:22:18,1084621697418973184,@ABC About time.,0.006,0.205,0.082,0.045,0.086,0.089,0.072,0.204,0.120
68086,1084622080715284480,With a new Democratic ally in the governor's o...,2019-01-14 01:22:18,1084621697418973184,@ABC https://t.co/j4dPKaPpiS,0.029,0.304,0.174,0.103,0.124,0.128,0.130,0.270,0.162
646493,1084622405559930880,Los Angeles Teachers Are Moving Forward With A...,2019-01-14 01:23:34,1084622016836030464,@NPR https://t.co/fsmYLlhRKq,0.032,0.263,0.124,0.147,0.085,0.079,0.074,0.231,0.084

In [8]:
# 1239325 (drop_duplicates(), low_memory=False)
# 1214909 [-24416] (drop_duplicates())
# 1114396 [-100513] (drop_duplicates('comment_id') condicionado, drop_duplicates(), low_memory=False)
ireplies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1114396 entries, 162471 to 646493
Data columns (total 14 columns):
 #   Column                           Non-Null Count    Dtype
---  ------                           --------------    -----
 0   comment_id                       1114396 non-null  object
 1   news_tweet_text                  1114396 non-null  object
 2   comment_tweet_date               1114396 non-null  object
 3   in_reply_to_news_id              1114396 non-null  object
 4   comment_tweet_text               1114396 non-null  object
 5   perspective_attack_on_author     1031324 non-null  float64
 6   perspective_attack_on_commenter  1031324 non-null  float64
 7   perspective_identity_attack      1031324 non-null  float64
 8   perspective_inflammatory         1031324 non-null  float64
 9   perspective_insult               1031324 non-null  float64
 10  perspective_profanity            1031324 non-null  float64
 11  perspective_severe_toxicity      1031324 non-null  float64
 12  perspective_threat               1031324 non-null  float64
 13  perspective_toxicity             1031324 non-null  float64
dtypes: float64(9), object(5)
memory usage: 127.5+ MB

### 'comment_id'

In [9]:
# linhas com COMMENT_ID em notação cientifica
commID=ireplies[ireplies[['comment_id']]
         .apply(lambda x: x.str.contains(',|E|e', regex=True))
         .any(axis=1)]
commID.head()

,comment_id,news_tweet_text,comment_tweet_date,in_reply_to_news_id,comment_tweet_text,perspective_attack_on_author,perspective_attack_on_commenter,perspective_identity_attack,perspective_inflammatory,perspective_insult,perspective_profanity,perspective_severe_toxicity,perspective_threat,perspective_toxicity
162471,"1,07836665916813E+018",Michelle Obama named America's most admired wo...,2018-12-27 16:09:32,"1,07832199495598E+018",@CBSNews Bahahaha: (1) that’s a dude,0.014124,0.344992,0.149827,0.067771,0.170093,0.163528,0.161568,0.202148,0.189273
162478,"1,07953981201571E+018",The return of slapstick comedy duo Laurel &amp,2018-12-31 00:29:50,"1,07953506114843E+018",@CBSNews أنين الصمت يقدم ⚔ #Thala عيدكم دماء...,0.000154,0.003633,0.268245,0.006973,0.192659,0.234862,0.278115,0.383201,0.231934
162495,"1,0795680349797E+018",The return of slapstick comedy duo Laurel &amp,2018-12-31 00:29:50,"1,07953506114843E+018",@CBSNews They were Comedian Magicians,0.011328,0.211965,0.145323,0.182571,0.241023,0.144097,0.150055,0.243645,0.231325
162480,"1,07953638549164E+018",The return of slapstick comedy duo Laurel &amp,2018-12-31 00:29:50,"1,07953506114843E+018",@CBSNews Is this word play for the return of d...,0.012386,0.416748,0.160337,0.192520,0.092686,0.035924,0.024335,0.073339,0.142476
162489,"1,07953567324437E+018",The return of slapstick comedy duo Laurel &amp,2018-12-31 00:29:50,"1,07953506114843E+018",@CBSNews Liberals will declare their comedy ro...,0.005264,0.535793,0.694272,0.727929,0.524430,0.293183,0.324584,0.249476,0.599444

In [10]:
# 32 (low_memory=False and drop_duplicates())
# 28 (drop_duplicates(comment id, ..) com condição)
len(commID)

28

In [11]:
# DROP das linhas presentes em commID [notação cientifica em 'comment_id']
ireplies.drop(commID.index,inplace=True)

### 'in_reply_to_news_id'

In [12]:
# linhas com IN_REPLY_TO_NEWS_ID em notação cientifica
iRep2News = ireplies[ireplies[['in_reply_to_news_id']]
             .apply(lambda x: x.str.contains(',|E|e', regex=True))
             .any(axis=1)]
iRep2News.head()

,comment_id,news_tweet_text,comment_tweet_date,in_reply_to_news_id,comment_tweet_text,perspective_attack_on_author,perspective_attack_on_commenter,perspective_identity_attack,perspective_inflammatory,perspective_insult,perspective_profanity,perspective_severe_toxicity,perspective_threat,perspective_toxicity
657948,1078515243108560896,Whatever journey you're on at any given moment...,2018-12-27 13:46:00,1.078285872942932e+18,@NPR #EverythingSucks was wonderful! https://t...,0.016036,0.096374,0.107122,0.050509,0.064979,0.052423,0.071207,0.160513,0.072206
1774376,1078286751913922560,Whatever journey you're on at any given moment...,2018-12-27 13:46:00,1.078285872942932e+18,@NPR Hey @MarcEvanJackson you made the list.,0.049761,0.727617,0.232932,0.199212,0.502453,0.380414,0.278340,0.235042,0.438031
662615,1078429567138684928,Whatever journey you're on at any given moment...,2018-12-27 13:46:00,1.078285872942932e+18,"@NPR ""The sad, exciting, adventurous, devastat...",0.107607,0.148876,0.229633,0.472787,0.575282,0.665248,0.527640,0.276153,0.714343
662356,1078301882467184640,Whatever journey you're on at any given moment...,2018-12-27 13:46:00,1.078285872942932e+18,@NPR @HorsleyScott Great job @lindaholmes ! Do...,0.051831,0.079114,0.153026,0.139494,0.160164,0.167155,0.224986,0.220077,0.211471
727780,1078292204211167232,The Guatemalan boy who died on Christmas Eve w...,2018-12-27 13:46:06,1.078285898e+18,@nytimes His parents are responsible for bring...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# 131961 (drop_duplicates(), low_memory=False)
# 98332 (drop_duplicates(), low_memory=False, drop_duplicates(comment_id, ...) condicionado)
# 32 (drop_duplicates(), low_memory=True)
len(iRep2News)

98304

In [14]:
# DROP das linhas presentes em iRep2News [notação científica em 'in_reply_to_news_id']
ireplies.drop(iRep2News.index,inplace=True)

### 'comment_id' e 'in_reply_to_news_id' [object => int 64]

In [15]:
# Alteração de TIPOS das colunas 'comment_it' e 'in_reply_to_news_id' object->int64
ireplies = ireplies.astype({"comment_id": int, "in_reply_to_news_id": int})
ireplies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1016064 entries, 209661 to 646493
Data columns (total 14 columns):
 #   Column                           Non-Null Count    Dtype
---  ------                           --------------    -----
 0   comment_id                       1016064 non-null  int64
 1   news_tweet_text                  1016064 non-null  object
 2   comment_tweet_date               1016064 non-null  object
 3   in_reply_to_news_id              1016064 non-null  int64
 4   comment_tweet_text               1016064 non-null  object
 5   perspective_attack_on_author     1016064 non-null  float64
 6   perspective_attack_on_commenter  1016064 non-null  float64
 7   perspective_identity_attack      1016064 non-null  float64
 8   perspective_inflammatory         1016064 non-null  float64
 9   perspective_insult               1016064 non-null  float64
 10  perspective_profanity            1016064 non-null  float64
 11  perspective_severe_toxicity      1016064 non-null  float64
 12  perspective_threat               1016064 non-null  float64
 13  perspective_toxicity             1016064 non-null  float64
dtypes: float64(9), int64(2), object(3)
memory usage: 116.3+ MB

### Explorar comment_tweet_text

Todos começam por @?

Algum com apenas @etc no início?

# Merge

In [10]:
items = pd.read_csv('items.csv') # NewsItems.csv já tratado
items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42706 entries, 0 to 42705
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   news_id          42706 non-null  int64
 1   newsoutlet_id    42706 non-null  int64
 2   news_tweet_date  42706 non-null  object
 3   news_url         42706 non-null  object
 4   new_title        42633 non-null  object
 5   news_date        26839 non-null  object
 6   news_text        42183 non-null  object
 7   single_news_id   42706 non-null  int64
dtypes: int64(3), object(5)
memory usage: 2.6+ MB

In [24]:
it_irep = pd.merge(items, ireplies, left_on='news_id',right_on='in_reply_to_news_id', how="left")

In [25]:
it_irep.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000525 entries, 0 to 1000524
Data columns (total 22 columns):
 #   Column                           Non-Null Count    Dtype
---  ------                           --------------    -----
 0   news_id                          1000525 non-null  int64
 1   newsoutlet_id                    1000525 non-null  int64
 2   news_tweet_date                  1000525 non-null  object
 3   news_url                         1000525 non-null  object
 4   new_title                        995759 non-null   object
 5   news_date                        310144 non-null   object
 6   news_text                        990187 non-null   object
 7   single_news_id                   1000525 non-null  int64
 8   comment_id                       988925 non-null   float64
 9   news_tweet_text                  988925 non-null   object
 10  comment_tweet_date               988925 non-null   object
 11  in_reply_to_news_id              988925 non-null   float64
 12  comment_tweet_text               988925 non-null   object
 13  perspective_attack_on_author     988925 non-null   float64
 14  perspective_attack_on_commenter  988925 non-null   float64
 15  perspective_identity_attack      988925 non-null   float64
 16  perspective_inflammatory         988925 non-null   float64
 17  perspective_insult               988925 non-null   float64
 18  perspective_profanity            988925 non-null   float64
 19  perspective_severe_toxicity      988925 non-null   float64
 20  perspective_threat               988925 non-null   float64
 21  perspective_toxicity             988925 non-null   float64
dtypes: float64(11), int64(3), object(8)
memory usage: 175.6+ MB

In [26]:
print('# Missing values #\n')
for column in items:
    bool_isnull = items[column].isnull()
    print(f'{column}: {len(items[bool_isnull])}')

# Missing values #

news_id: 0
newsoutlet_id: 0
news_tweet_date: 0
news_url: 0
new_title: 73
news_date: 15867
news_text: 523
single_news_id: 0

In [27]:
print('# Missing values #\n')
for column in ireplies:
    bool_isnull = ireplies[column].isnull()
    print(f'{column}: {len(ireplies[bool_isnull])}')

# Missing values #

comment_id: 0
news_tweet_text: 0
comment_tweet_date: 0
in_reply_to_news_id: 0
comment_tweet_text: 0
perspective_attack_on_author: 0
perspective_attack_on_commenter: 0
perspective_identity_attack: 0
perspective_inflammatory: 0
perspective_insult: 0
perspective_profanity: 0
perspective_severe_toxicity: 0
perspective_threat: 0
perspective_toxicity: 0

In [19]:
print('# Missing values #\n')
for column in it_irep:
    bool_isnull = it_irep[column].isnull()
    print(f'{column}: {len(it_irep[bool_isnull])}')

# Missing values #

news_id: 0
newsoutlet_id: 0
news_tweet_date: 0
news_url: 0
new_title: 4766
news_date: 5638
news_text: 10338
comment_id: 11600
news_tweet_text: 11600
comment_tweet_date: 11600
in_reply_to_news_id: 11600
comment_tweet_text: 11600
perspective_attack_on_author: 11600
perspective_attack_on_commenter: 11600
perspective_identity_attack: 11600
perspective_inflammatory: 11600
perspective_insult: 11600
perspective_profanity: 11600
perspective_severe_toxicity: 11600
perspective_threat: 11600
perspective_toxicity: 11600

In [20]:
# valores de news_ids(aka 'in_reply_to_news_id') no ireplies
news_id_rep = ireplies['in_reply_to_news_id'].unique()

# notícias (news_ids) que estão no items mas não estão no ireplies, i.e., não têm comentários associados
news_notin_items = items[~items.news_id.isin(news_id_rep)]
news_notin_items.count()

news_id            11600
newsoutlet_id      11600
news_tweet_date    11600
news_url           11600
new_title          11599
news_date          11599
news_text          11269
dtype: int64

In [33]:
items.news_id.isin(news_id_rep).value_counts()

True     31106
False    11600
Name: news_id, dtype: int64

In [34]:
news_notin_items

,news_id,newsoutlet_id,news_tweet_date,news_url,new_title,news_date,news_text
56,1078675596153159680,28785486,2018-12-28 15:34:37,https://abcn.ws/2CAoXfS,Missing Colorado mom's parents win temporary c...,None,A Colorado man accused of murdering his fiance...
305,1083444498603040769,28785486,2019-01-10 19:24:32,http://abcn.ws/2CZfSxm,"As Trump heads to Texas border, he says he 'pr...",None,As he left Thursday morning to head to the Tex...
486,1082305285992009729,28785486,2019-01-07 15:57:43,https://www.pscp.tv/w/bwNudjM3Mzg2fDF2T3h3WmVa...,"ABC News: ""We're live in Nantucket at the cour...",None,NaN
525,1083834382115196928,28785486,2019-01-11 21:13:48,https://abcn.ws/2D1JcTW,Trump directs Army Corps of Engineers to find ...,None,The White House has directed the Army Corps of...
563,1079792353353842689,28785486,2018-12-31 17:32:13,https://abcn.ws/2CGEbQx,"Fast-moving storm will bring rain, gusty winds...",None,Two different systems will combine Monday to p...
...,...,...,...,...,...,...,...
42682,1082491855021977600,6107422,2019-01-08 04:19:04,https://www.thetimes.co.uk/article/saudi-teena...,UN to care for Saudi girl Rahaf Mohammed Alqun...,None,"We are sorry, you need to be a subscriber to w..."
42687,1080363073578418176,6107422,2019-01-02 07:20:03,https://www.thetimes.co.uk/article/nasas-new-h...,Nasa probe extends horizons of mankind with fl...,None,The New Horizons probe managed to gather data ...
42690,1083867252057886721,6107422,2019-01-11 23:24:24,https://www.thetimes.co.uk/article/flybe-sold-...,Flybe sold for £2.2m in cut-price deal,None,Flybe has struggled to make a profit since flo...
42691,1082895040182128640,6107422,2019-01-09 07:01:11,https://www.thetimes.co.uk/article/carillion-m...,Carillion’ Midland Metropolitan hospital to be...,None,The hospital as it should have been. It has in...
42697,1083492778540257282,6107422,2019-01-10 22:36:23,https://www.thetimes.co.uk/article/photographe...,Photographer Eva O’Leary wins plaudits for mir...,None,"Eva O’Leary says some subjects were confident,..."

In [21]:
news_notin_items.nunique()

news_id            11600
newsoutlet_id         27
news_tweet_date    11197
news_url            9923
new_title           8308
news_date           5682
news_text           8462
dtype: int64

In [22]:
items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42706 entries, 0 to 42705
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   news_id          42706 non-null  int64
 1   newsoutlet_id    42706 non-null  int64
 2   news_tweet_date  42706 non-null  object
 3   news_url         42706 non-null  object
 4   new_title        42633 non-null  object
 5   news_date        42573 non-null  object
 6   news_text        42183 non-null  object
dtypes: int64(2), object(5)
memory usage: 2.3+ MB

In [23]:
it_irep[it_irep.index.isin(news_notin_items.index)]

,news_id,newsoutlet_id,news_tweet_date,news_url,new_title,news_date,news_text,comment_id,news_tweet_text,comment_tweet_date,in_reply_to_news_id,comment_tweet_text,perspective_attack_on_author,perspective_attack_on_commenter,perspective_identity_attack,perspective_inflammatory,perspective_insult,perspective_profanity,perspective_severe_toxicity,perspective_threat,perspective_toxicity
56,1084275179331772416,28785486,2019-01-13 02:25:22,https://abcn.ws/2Fv3iri,Drone captures California man surfing with dol...,None,"Breathtaking drone video of a pod of friendly,...",1.084306e+18,SURF BUDDIES: Incredible experience for this s...,2019-01-13 02:25:22,1.084275e+18,@ABC https://t.co/oqjYXHokNg,0.028921,0.304418,0.173827,0.103305,0.123528,0.127656,0.130282,0.270158,0.161517
305,1081379589711167489,28785486,2019-01-05 02:39:19,https://abcn.ws/2CPxBr3,GOP decries Pelosi's muted reaction as Dems de...,None,As newly minted Rep. Rashida Tlaib refused to ...,1.081539e+18,GOP decries Pelosi's muted reaction as Dems de...,2019-01-05 02:39:19,1.081380e+18,@ABC Appropriate response to those hypocrite m...,0.149598,0.818961,0.476302,0.643589,0.853236,0.858920,0.747318,0.412886,0.837824
486,1083901643027025920,28785486,2019-01-12 01:41:04,https://abcn.ws/2D5NI49,Federal workers rally in Boston to demand end ...,None,Federal workers who aren't getting paychecks a...,1.083903e+18,Federal workers who aren't getting paychecks a...,2019-01-12 01:41:04,1.083902e+18,@ABC If Republicans can't find common ground w...,0.000444,0.016892,0.689474,0.807975,0.782563,0.579859,0.452784,0.403290,0.717940
525,1079638749359886336,28785486,2018-12-31 07:21:51,https://abcn.ws/2EWgnJZ,Note says Britain's queen 'naturally' wanted n...,None,A newly discovered note in the U.K.'s National...,1.079642e+18,A newly discovered note in the U.K.'s National...,2018-12-31 07:21:51,1.079639e+18,@ABC When will all those wasted riches go to t...,0.011809,0.240449,0.248414,0.277415,0.218083,0.158910,0.162911,0.320454,0.251956
563,1080975124520714240,28785486,2019-01-03 23:52:07,https://abcn.ws/2CO4dl5,Alabama woman to receive 'miracle' kidney dona...,None,The new year is bringing an extreme act of kin...,1.080976e+18,"Alabama woman to receive ""miracle"" kidney dona...",2019-01-03 23:52:07,1.080975e+18,@ABC What a great story!!,0.007612,0.070879,0.106945,0.017848,0.098222,0.128767,0.155338,0.276928,0.138237
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42682,1081375496435306496,28785486,2019-01-05 02:23:03,https://abcn.ws/2FahohS,Congresswoman Rashida Tlaib should apologize f...,None,I was born on the West side of Detroit; in fac...,1.081396e+18,OPINION: Congresswoman Rashida Tlaib should ap...,2019-01-05 02:23:03,1.081375e+18,@ABC @matthewjdowd Has any Democrat condemned ...,0.026096,0.428929,0.323396,0.349853,0.335626,0.232901,0.205861,0.298448,0.375931
42687,1081375496435306496,28785486,2019-01-05 02:23:03,https://abcn.ws/2FahohS,Congresswoman Rashida Tlaib should apologize f...,None,I was born on the West side of Detroit; in fac...,1.081440e+18,OPINION: Congresswoman Rashida Tlaib should ap...,2019-01-05 02:23:03,1.081375e+18,@ABC @matthewjdowd If she should then wtf has ...,0.005923,0.084933,0.324028,0.441282,0.452698,0.647918,0.506960,0.319302,0.534762
42690,1081375496435306496,28785486,2019-01-05 02:23:03,https://abcn.ws/2FahohS,Congresswoman Rashida Tlaib should apologize f...,None,I was born on the West side of Detroit; in fac...,1.081395e+18,OPINION: Congresswoman Rashida Tlaib should ap...,2019-01-05 02:23:03,1.081375e+18,@ABC @matthewjdowd https://t.co/rloT2AopUA,0.021076,0.158680,0.163517,0.112559,0.175519,0.244319,0.227599,0.250931,0.202623
42691,1081375496435306496,28785486,2019-01-05 02:23:03,https://abcn.ws/2FahohS,Congresswoman Rashida Tlaib should apologize f...,None,I was born on the West side of Detroit; in fac...,1.081387e+18,OPINION: Congresswoman Rashida Tlaib should ap...,2019-01-05 02:23:03,1.081375e+18,@ABC @matthewjdowd Trump should apologize for ...,0.031837,0.415905,0.641727,0.610448,0.813040,0.893975,0.821408,0.849635,0.871816
42697,1081375496435306496,28785486,2019-01-05 02:23:03,https://abcn.ws/2FahohS,Congresswoman Rashida Tlaib should apologize f...,None,I was born on the West side of Detroit; in fac...,1.081422e+18,OPINION: Congresswoman Rashida Tlaib should ap...,2019-01-05 02:23:03,1.081375e+18,@ABC @matthewjdowd Dems becoming Trump and Tru...,0.021922,0.386389,0.126111,0.268073,0.238585,0.223785,0.177173,0.209502,0.294754

In [24]:
news_notin_items['newsoutlet_id'].unique()

array([  28785486,     612473,   16343974, 1020058453,   15012486,
           759251,   14511951,   14173315,    5392522,   95431448,
           807095,    3108351,    2467791,   14293310,   15754281,
          7309052,   17895820,  111556423,   16887175,  271413771,
         21866939,  138749160,    7587032,   87818409,   16973333,
         34655603,    6107422])

In [25]:
ireplies[ireplies['comment_id']==np.nan]

Empty DataFrame
Columns: [comment_id, news_tweet_text, comment_tweet_date, in_reply_to_news_id, comment_tweet_text, perspective_attack_on_author, perspective_attack_on_commenter, perspective_identity_attack, perspective_inflammatory, perspective_insult, perspective_profanity, perspective_severe_toxicity, perspective_threat, perspective_toxicity]
Index: []

In [26]:
ireplies[ireplies['in_reply_to_news_id']==np.nan]

Empty DataFrame
Columns: [comment_id, news_tweet_text, comment_tweet_date, in_reply_to_news_id, comment_tweet_text, perspective_attack_on_author, perspective_attack_on_commenter, perspective_identity_attack, perspective_inflammatory, perspective_insult, perspective_profanity, perspective_severe_toxicity, perspective_threat, perspective_toxicity]
Index: []

In [27]:
it_irep[it_irep.isnull()]

,news_id,newsoutlet_id,news_tweet_date,news_url,new_title,news_date,news_text,comment_id,news_tweet_text,comment_tweet_date,in_reply_to_news_id,comment_tweet_text,perspective_attack_on_author,perspective_attack_on_commenter,perspective_identity_attack,perspective_inflammatory,perspective_insult,perspective_profanity,perspective_severe_toxicity,perspective_threat,perspective_toxicity
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
# export do csv
#ireplies.to_csv('ireplies.csv', index=False)